version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:16.2'
    build:
      context: .
    container_name: spring-boot-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_VERSION=jdk-17

  db:
    image: 'postgres:16.2-alpine'
    container_name: postgres-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres